[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 3000

[client]
showErrorDetails = true
toolbarMode = "minimal"
